TIME_TREND_COL_NAME = "time_trend"

SECOND_QUARTER_COL_NAME = "Q_2"
THIRD_QUARTER_COL_NAME = "Q_3"
FOURTH_QUARTER_COL_NAME = "Q_4"
QUARTER_COL_NAMES = [
    SECOND_QUARTER_COL_NAME,
    THIRD_QUARTER_COL_NAME,
    FOURTH_QUARTER_COL_NAME,
]

FEATURE_LIST = QUARTER_COL_NAMES + [
    TIME_TREND_COL_NAME,
    "const",  # for statsmodels OLS intercept
]
